CREATE FUNCTION check_opponent_different_from_club_fn(opponent_name VARCHAR(255), club_id INT) RETURNS BOOLEAN AS $$
BEGIN
    RETURN opponent_name <> (SELECT title FROM club WHERE club_id = club_id);
END;
$$ LANGUAGE plpgsql;

create table match(
	match_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  	stadium_id int references stadium(stadium_id),
  	referee_id int references referee(referee_id),
	club_id int references club(club_id),
	result text not null,
	match_date date not null,
	lineups_of_teams text,
	opponent varchar(255) not null,
	CONSTRAINT check_opponent_different_from_club CHECK (check_opponent_different_from_club_fn(opponent, club_id)),
    CONSTRAINT opponent_exists_in_club FOREIGN KEY (opponent) REFERENCES club(title)
)