CREATE TABLE IF NOT EXISTS orders(
  order_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_id int REFERENCES customers(customer_id),
  order_date date  NOT NULL default current_date,
  ship_date date,
  paid_date date,
  status char(1)
)